# Generated by Django 5.0.8 on 2024-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
